name: Docker Image CI

on:
  push:
    branches: [ release-4.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openshift-console-modified:4.7
