name: Build and push production image

on:
  push:
    branches: [ release-4.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # build actual image
    - name: Build the Docker production image
      run: docker build . --file Dockerfile --tag mehbos/openshift-console-modified:4.7

    # and push it to dockerHub
    - name: Push docker image
      env:
        docker_uid: ${{ secrets.DOCKER_USERNAME }}
        docker_pwd: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$docker_uid" -p "$docker_pwd" && \
        docker push mehbos/openshift-console-modified:4.7
