name: Build and push dev image

on:
  push:
    branches: [ release-4.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker dev image
      run: docker build . --file Dockerfile.dev --tag mehbos/openshift-console-modified:dev-4.7
    - name: Push docker image
      env:
        docker_uid: ${{ secrets.DOCKER_USERNAME }}
        docker_pwd: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$docker_uid" -p "$docker_pwd" && \
        docker push mehbos/openshift-console-modified:dev-4.7
