name: Docker Image CI

on:
  push:
    branches: [ release-4.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        docker_uid: ${{ secrets.DOCKER_USERNAME }}
        docker_pwd: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u "$docker_uid" -p "$docker_pwd" && \
        docker build . --file Dockerfile --tag mehbos/openshift-console-modified:4.7 && \
        docker push mehbos/openshift-console-modified:4.7
